galaxy_info:
  author: HybridCloud05 Team03
  description: Grafana 설치 및 Prometheus 데이터 소스, 대시보드 설정 자동화
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.1
  galaxy_tags: 
    - monitoring
    - grafana
    - prometheus
    - dashboard

dependencies: []
